/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package TP6.vistas;

import TP6.Entidades.Producto;
import java.util.TreeSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alakyan
 */
public class porPrecio extends javax.swing.JInternalFrame {
private TreeSet<Producto> productos;
   private DefaultTableModel modelo= new DefaultTableModel(){ 
    public boolean isCellEditable(int f,int c){
        return false;
        }
    };
    /**
     * Creates new form porPrecio
     * @param productos
     */
    public porPrecio(TreeSet<Producto> productos) {
     initComponents();
     this.productos=productos;
        armarCabecera();
        }
    
    private void armarCabecera(){
        modelo.addColumn("Codigo");
        modelo.addColumn("Nombre");
        modelo.addColumn("Precio");
        modelo.addColumn("Stock");
        jtPrecio.setModel(modelo);
        }
    
    private void borrarFilas(){
        int filas=jtPrecio.getRowCount()-1;        
        for (int f = filas; f >= 0; f--) {
            modelo.removeRow(f);
        }
    }
    
    private double mayorPrecio(){
        double mayor= 0;
        for (Producto producto : productos) {
           if(producto.getPrecio()>=mayor){
               mayor=producto.getPrecio();
           } 
        }
        return mayor;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtPrecioMenor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtPrecioMayor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPrecio = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Listado por Precio");

        jLabel2.setText("Entre $: ");

        jtPrecioMenor.setText("0");
        jtPrecioMenor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtPrecioMenorKeyReleased(evt);
            }
        });

        jLabel3.setText("y");

        jtPrecioMayor.setText(" ");
        jtPrecioMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPrecioMayorActionPerformed(evt);
            }
        });
        jtPrecioMayor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtPrecioMayorKeyReleased(evt);
            }
        });

        jtPrecio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtPrecio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(160, 160, 160))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtPrecioMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jtPrecioMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtPrecioMenor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtPrecioMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtPrecioMenorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPrecioMenorKeyReleased
        borrarFilas();
        double producto,producto2;
        try{
        producto=Double.parseDouble(jtPrecioMenor.getText());
        if(jtPrecioMenor.getText().equals("")){
            producto2=mayorPrecio();
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Ingrese el precio en decimales!");
            return;
        }
        
        try{
        producto2=Double.parseDouble(jtPrecioMayor.getText());
        if(jtPrecioMayor.getText().equals("")){
            producto2=mayorPrecio();
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Ingrese el precio en decimales!");
            return;
        }
        
        for(Producto p:productos){
            if(p.getPrecio()>=producto && p.getPrecio()<=producto2){
            modelo.addRow(new Object[]{p.getCodigo(),p.getDescripcion(),p.getPrecio(),p.getStock()});
            }
        }
    }//GEN-LAST:event_jtPrecioMenorKeyReleased

    private void jtPrecioMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPrecioMayorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtPrecioMayorActionPerformed

    private void jtPrecioMayorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPrecioMayorKeyReleased
      borrarFilas();
        double producto,producto2;
        try{
        producto=Double.parseDouble(jtPrecioMenor.getText());
        if(jtPrecioMenor.getText().equals("")){
            producto2=mayorPrecio();
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Ingrese el precio en decimales!");
            return;
        }
        
        try{
        producto2=Double.parseDouble(jtPrecioMayor.getText());
        if(jtPrecioMayor.getText().equals("")){
            producto2=mayorPrecio();
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Ingrese el precio en decimales!");
            return;
        }
        
        for(Producto p:productos){
            if(p.getPrecio()>=producto && p.getPrecio()<=producto2){
            modelo.addRow(new Object[]{p.getCodigo(),p.getDescripcion(),p.getPrecio(),p.getStock()});
            }
        }        
    }//GEN-LAST:event_jtPrecioMayorKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtPrecio;
    private javax.swing.JTextField jtPrecioMayor;
    private javax.swing.JTextField jtPrecioMenor;
    // End of variables declaration//GEN-END:variables
}
